openapi: 3.0.0
info:
title: Believer Auth APIs
version: 1.0.0
paths:
/api/auth/register:
post:
summary: Register a new user
requestBody:
required: true
content:
application/json:
schema:
type: object
properties:
name:
type: string
email:
type: string
phone:
type: string
password:
type: string
responses:
'201':
description: Created
/api/auth/login:
post:
summary: Login
requestBody:
required: true
content:
application/json:
schema:
type: object
properties:
email:
type: string
password:
type: string
responses:
'200':
description: OK